create table critic
(
    id          integer generated by default as identity
        primary key,
    information varchar(255),
    name        varchar(255),
    surname     varchar(255)
);
create table genre
(
    id          integer generated by default as identity
        primary key,
    description varchar(255),
    name        varchar(255)
);
create table movie
(
    id          integer generated by default as identity
        primary key,
    description varchar(255),
    length      integer not null,
    name        varchar(255),
    score       real    not null,
    year_release        integer not null
);
create table review
(
    id        integer generated by default as identity
        primary key,
    date      date,
    message   varchar(255),
    score     real not null,
    critic_id integer
        constraint fk87kl56bxw1tepiu19cjy24v5c
            references critic,
    movie_id  integer
        constraint fk8378dhlpvq0e9tnkn9mx0r64i
            references movie
);
create table genre_movies
(
    movie_id integer not null
        constraint fko0p8dudi1ar9iy1oiq7gesymb
            references movie,
    genre_id integer not null
        constraint fkna0q0v9ce4wywop8o440cv70p
            references genre
);
